<a href="https://colab.research.google.com/github/Nikilpn/machine_learning_projects/blob/master/Naive_bayes_theorem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Outlook list
outlook = ["sunny", "sunny", "overcast", "rainy", "rainy", "rainy", "overcast",
           "sunny", "sunny", "rainy", "sunny", "overcast", "overcast", "rainy"]

# Temperature list
temperature = ["hot", "hot", "hot", "mild", "cool", "cool", "cool",
        "mild", "cool", "mild", "mild", "mild", "hot", "mild"]

# Humidity list
humidity = ["high", "high", "high", "high", "normal", "normal", "normal",
            "high", "normal", "normal", "normal", "high", "normal", "high"]

# Windy list
wind = ["Weak", "Strong", "Weak", "Weak", "Weak", "Strong", "Strong",
        "Weak", "Weak", "Weak", "Strong", "Strong", "Weak", "Strong"]


# Play list (Target variable)
play = ["no", "no", "yes", "yes", "yes", "no", "yes",
        "no", "yes", "yes", "yes", "yes", "yes", "no"]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
outlook_encoder=lb.fit_transform(outlook)
outlook_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [ ]:
lb=LabelEncoder()
temperature_encoder=lb.fit_transform(temperature)
temperature_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [ ]:
lb=LabelEncoder()
wind_encoder=lb.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [ ]:
lb=LabelEncoder()
humidity_encoder=lb.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [ ]:
#zip
features=list(zip(outlook_encoder,temperature_encoder,humidity_encoder,wind_encoder))
features

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

In [ ]:
#model Creation
#Naive_bayes
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(features,play)
print(model.predict([[2,0,0,0]]))

['no']
